### ISSUE TITLE
Documentation: Introduction section, What is ByConity

### ISSUE THREAD

**Issue by Joshalphonse** [ByConity/byconity.github.io#153]
The Documentation should have a 'What is ByConity' paragraph. Although ByConity is explained on the landing page, it would be very beneficial to have a paragraph on what ByConity is within the introduction section of the documentation. This is usually best practice. When we share the link to our documentation with a user who has no idea what ByConity is it would be the first thing they see.

**Comment by WillemJiang** [comment]
@Joshalphonse  Do you mind add a paragraph of it in [the quick start](https://github.com/ByConity/byconity.github.io/blob/main/docs/introduction/quick-start.mdx) of ByConity.

**Comment by wbtiger** [comment]
https://byconity.github.io/zh-cn/docs/introduction/what-is-byconity
