### ISSUE TITLE
Supporting variable in compiling doc

### ISSUE THREAD

**Issue by hustnn** [ByConity/byconity.github.io#158]
It is easier for doc update when version (x.y.z) change.

**Comment by pswai** [comment]
@hustnn We can explore envvar to control it, probably in 2 steps:
- [ ] manually updates envvar to trigger build
- [ ] auto update envvar when a new version is available

The second one can be tricky but going to be very useful

**Comment by WillemJiang** [comment]
We need to introduce [document versioning](https://docusaurus.io/docs/versioning) into the website. When we release ByCounity, we need to create a new version of a document on the website.

**Comment by WillemJiang** [comment]
Fix this problem by applying below two patches.

https://github.com/ByConity/byconity.github.io/pull/206
https://github.com/ByConity/byconity.github.io/pull/207
