### ISSUE TITLE
Link does not work in the docker wrapper deployment documentation

### ISSUE THREAD

**Issue by Joshalphonse** [ByConity/byconity.github.io#160]
In the docker wrapper deployment documentation page there is a link to the guide produces a 404 error and the guide does not show up. 

<img width="1635" alt="Screenshot 2023-06-02 at 1 37 45 PM" src="https://github.com/ByConity/byconity.github.io/assets/11986958/f591e709-3504-484f-86cc-8494ab05140c">

**Comment by WillemJiang** [comment]
@Joshalphonse The broken link is updated.
