### ISSUE TITLE
Chinese translation of s3 upgrade checklist

### ISSUE THREAD

**Issue by WillemJiang** [ByConity/byconity.github.io#208]
We need to provide translation for https://byconity.github.io/docs/advanced-guide/0.2.0_s3_upgrade_checklist

**Comment by YuanHanzhong** [comment]
The link shows page not found.
![image](https://github.com/ByConity/byconity.github.io/assets/57024493/1fd18776-8ffe-4774-a087-462431fa52ce)

**Comment by wbtiger** [comment]
> The link shows page not found. ![image](https://private-user-images.githubusercontent.com/57024493/318184066-1fd18776-8ffe-4774-a087-462431fa52ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTc1NjQsIm5iZiI6MTcxODYxNzI2NCwicGF0aCI6Ii81NzAyNDQ5My8zMTgxODQwNjYtMWZkMTg3NzYtOGZmZS00Nzc0LWEwODctNDYyNDMxZmE1MmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA5NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YTVjZDdiNWUzNWM4ZWUyZDVlYWU3YjI1MjA3ZjAzNWQ1NjFkZTE5NTkwNDJmNGUxZjIzMjBmOTYyZjg1MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eX7ty_fiP4xmxyAaLSsMGJuj-aPEKApTgCloNBy8XYA)

https://byconity.github.io/zh-cn/docs/deployment/upgrade#%E5%8D%87%E7%BA%A7%E5%9F%BA%E4%BA%8Es3%E5%AD%98%E5%82%A8%E7%9A%84%E9%9B%86%E7%BE%A4%E4%BB%85%E9%80%82%E7%94%A8020%E4%B9%8B%E5%89%8D%E7%9A%84%E7%89%88%E6%9C%AC
