### ISSUE TITLE
Where is the source code of byconity.github.io?

### ISSUE THREAD

**Issue by WillemJiang** [ByConity/byconity.github.io#70]
I just found the master branch is the deploied pages, but I cannot find the source code repo of this website.

**Comment by WillemJiang** [comment]
@pswai  Thanks for the reply. But it isn't a good way to go. 

Put everything into a big repo could add a burden on the user and make it hard for the CI process; 
* If the network is not good enough, it will take a lot of time to download the repo, 
* It's hard for us to tell which part of the file is related to the website if we want to deploy it once the user submits a PR automatically.

**Comment by pswai** [comment]
@WillemJiang Totally agree for the network part. Regarding repo, as long as we have good monorepo management, it's actually not too bad.

Personally, I prefer everything related to the website is in a separate repo. But I also understand that if the documentation files (the markdowns) are not in the same repo with the source code, nobody will bother to update them 😅 

@Adora627 based on your experience, what would you suggest?

**Comment by WillemJiang** [comment]
For the Apache projects, we have separated the repo for the website. 
For the README and some instruction documents, it's better to put them into the source code repo

**Comment by pswai** [comment]
@WillemJiang  I see, let's do this?

[] Move the website source code here
[] Leave the raw doc files in the main repo
[] Setup a workflow to trigger a deployment when the doc files are updated
