### ISSUE TITLE
Using english name for docs directory and files 

### ISSUE THREAD

**Issue by WillemJiang** [ByConity/byconity.github.io#79]
Current we just use Chinese to name the docs directoriese and doc files, it's made the URL more complex. 
It's common practices to use the english name for the doc directory and docs name.

**Comment by pswai** [comment]
Yes I think this should be the default. It is more inclusive and makes maintenance easier

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pswai** [comment]
@WillemJiang @xxisxuxu I'll do a normalisation to all file names, let me come up with a PR. Typically this is what I propose:

* Use kebab-case for file names because it is more friendly for url
* File name must be all lower case
* Use the `title` front matter for the actual title
