### ISSUE TITLE
Deploying the PR preview website

### ISSUE THREAD

**Issue by WillemJiang** [ByConity/byconity.github.io#83]
It would be helpful to generate builds for each PR using [Netlify](https://www.netlify.com/) so that reviewers can try out the latest site built from the PR branch.

**Comment by pswai** [comment]
@WillemJiang We can do that. If we do so we might want to consider having the entire hosting there

**Comment by WillemJiang** [comment]
We can still use GitHub to host the website and Netlfiy to host the website SNAPSHOT when the PR is submitted.

**Comment by pswai** [comment]
> We can still use GitHub to host the website and Netlfiy to host the website SNAPSHOT when the PR is submitted.

Sounds good. Can you or @Adora627 assist on this?

**Comment by pswai** [comment]
@WillemJiang @Adora627 can you help applying for an open source plan? https://opensource-form.netlify.com/

**Comment by pswai** [comment]
@WillemJiang i'll try to apply an oss account adhering to https://www.netlify.com/legal/open-source-policy/

**Comment by pswai** [comment]
The preview looks good now
